version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    environment:
      BRANCHES: "+([0-9])?(.{+([0-9]),x}).x|main|next|next-major|beta|alpha"
    steps:
      - checkout
      - when:
          condition:
            not:
              matches:
                pattern: $BRANCHES
                value: << pipeline.git.branch >>
          steps:
            - run:
                name: Installation
                command: npm install
            - run:
                name: Setup Code Climate test-reporter
                command: |
                  # download test reporter as a static binary
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                  chmod +x ./cc-test-reporter
                  ./cc-test-reporter before-build      
            - run:
                name: Test runner
                command: npm run test:report
            - codecov/upload:
                file: './coverage/lcov.info'
            - run:
                name: Send coverage to Code Climate
                command: ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
      - when:
          condition:
            matches:
              pattern: $BRANCHES
              value: << pipeline.git.branch >>
          steps:
            - run:
                name: Release
                command: npm run semantic-release || true

workflows:
  version: 2
  deploy:
    jobs:
      - build
