version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: Installation
          command: npm install
      - run:
          name: Test Runner
          command: npm run test:coverage
      - codecov/upload:
          file: './coverage/lcov.info'
      - run:
          name: Release
          command: npm run semantic-release || true
