version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
        name: install
        command: npm install
      -run:
        name: Test Runner
        command: npm run test:coverage
      - codecov/upload:
        file: {{ coverage_report_filepath }}
      - run:
          name: release
          command: npm run semantic-release || true
